repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ".*?(.hex|.clvm|.clib|.clsp)"
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        args: # arguments to configure black
            - --line-length=120
            - --include='\.pyi?$'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: [types-aiofiles, types-click, types-setuptools, types-PyYAML]
      # This intentionally counters the settings in mypy.ini to allow a loose local
      # check and a strict CI check. This difference may or may not be retained long
      # term.
      args: [--no-warn-unused-ignores]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=120"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"
